### ISSUE TITLE
Declaration map support (.d.ts.map) to jump to source files

### ISSUE THREAD

**Issue by kalvenschraut** [vuejs/language-tools#1344]
In my mono repo I am generating a bunch of .d.ts.map files when running my dev scripts and I am noticing that when I goto definition using the typescript language server it will jump to the .ts source file. While using volar in takeover mode it is jumping to the .d.ts file  instead.

I can't find any documentation or other issues stating similar things so figured it either is not supported or there is some issue with my setup.  Once I get more time I can get a repro going if this is more specific to my case.

**Comment by gustavotoyota** [comment]
Bump. It took me nearly a month to find out this is a Volar problem.
This issue makes Go To Definition useless in typescript monorepos containing Vue apps.

**Comment by gustavotoyota** [comment]
Workaround for now is to use Typescript Vue Plugin instead of Take Over mode.

**Comment by johnsoncodehk** [comment]
Could you provide minimal reproduction?

**Comment by gustavotoyota** [comment]
1. Clone https://github.com/andrewthauer/ts-monorepo
2. Run `yarn install`
3. Run `yarn build`
4. Open the file packages/web/src/index.ts
5. With Take Over mode active, ctrl+click on `doubleNumbers`: It will take you to the build file (Bad)
6. With Typescript Vue Plugin active, ctrl+click on `doubleNumbers`: It will take you to the source file (Good)

**Comment by johnsoncodehk** [comment]
I just to remove project references and related settings for TypeScript LanguageService and it seems resolved the problem, but not sure if it cause to other problems, so I add a setting and you need clearly config `"volar.vueserver.noProjectReferences": true` in VSCode to enable this.

I will keep this issue open until confirm if this workaround is suitable.

**Comment by gustavotoyota** [comment]
It looks like it's now working with Take Over mode, thank you!

**Comment by kalvenschraut** [comment]
I am still having the same issues, but I am using coc-volar instead of the vscode extension. I think I was able to pass through the noProjectReferences correctly, but it still doesn't work for me. I don't use project references like in the first repro that was added.

@johnsoncodehk  added a repro for my case [here](https://github.com/RTVision/volar-declarations-sourcemap-jump-repro/tree/master). If you are not experiencing my issue in vscode with that option enabled, then I must not have passed it down correctly. Otherwise that option doesn't fix it for my case.

**Comment by yaegassy** [comment]
Hi @kalvenschraut, Update the `coc-volar` and give it a try. `:CocUpdate`

It seems that the response to reflect the `volar.vueserver.noProjectReferences` settings was missing in `coc-volar`.

**Comment by kalvenschraut** [comment]
> Hi @kalvenschraut, Update the `coc-volar` and give it a try. `:CocUpdate`
> 
> It appears that the `volar.vueserver.noProjectReferences` setting was missing from `coc-volar`.

Updated and appears to not be working with my setup still in my reproduction repo.

**Comment by johnsoncodehk** [comment]
@kalvenschraut It's because you have set up `"exports": { ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" } }` in packages/package-a/package.json, don't know why VSCode built-in TypeScript extension does not respect `exports` option, we have to check what is the correct behavior with `exports`.

You can config `"paths": { "package-a": ["../package-a/src/index.ts"] }` to packages/package-b/tsconfig.json as a workaround.

**Comment by blake-newman** [comment]
should be resolved with: https://github.com/volarjs/volar.js/pull/24

**Comment by segevfiner** [comment]
@blake-newman @johnsoncodehk Going to a Vue component in a library that has declaration maps doesn't seem to work in non-take over mode in Vue files, but it does work in ts files, which suggests there is still an issue with declaration map support in Volar.
