### ISSUE TITLE
In vue components, if a symbol is imported from 'vue' module, additional imports are not auto-completed.

### ISSUE THREAD

**Issue by michaeldaw** [vuejs/language-tools#2190]
example:
Start with an empty vue component.
Begin typing 'onMounted' and hit tab to auto-complete.
An import statement is created in which onMounted is imported from 'vue'.
Begin typing 'onUnmounted' and hit tab to auto-complete.
'onUnmounted' is not added to the imports from 'vue'.

Other modules seem to work fine. This only seems to happen with the 'vue' module.

https://user-images.githubusercontent.com/8949148/206842094-d50cbf07-91c5-4ba4-a772-491837c8d8e9.mp4

**Comment by LinusBorg** [comment]
FWIW: Works fine for me.

**Comment by Yooling-lei** [comment]
me too, v1.0.13

**Comment by mattersj** [comment]
That's indeed a bug and I assume it's caused by ambient modules: if you have them in your project (`declare module '...'`) you'll likely see this error instead of the actual completion.

Look closely at the video and check out a detailed description of the selected completion on the right side, there's an error `[TS Error] {}` (timecode is 0:11). That's because Volar fails to provide correct completion and throws an error here:

https://github.com/johnsoncodehk/volar/blob/cba2eba187b2d82e1d45dd86b3edeab0ca7caad6/plugins/typescript/src/services/completions/resolve.ts#L43-L48

You can try to reproduce these steps in a regular *.ts file with takeover mode **turning off** and everything will be working fine but once you enable takeover mode you'll get this error even in *.ts files.

I was testing this on `vue-router` as well and I got the same error after adding the following code in a *.d.ts file:
```ts
declare module 'vue-router' {}
export {};
```
<img width="928" alt="image" src="https://user-images.githubusercontent.com/28510814/207581469-004c066d-bbcf-4f21-909c-8f1ec4c03e6d.png">

But if I comment out the ambient declaration:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/28510814/207581621-162c6018-25df-449c-809a-7a10238f3f3e.png">

**Comment by jinyongp** [comment]
Another error occurs from v1.0.8

![image](https://user-images.githubusercontent.com/21158729/208621258-d9a6bb92-74db-43a4-b9f7-a4ea21ab9eb8.png)

How do I fix it?

**Comment by johnsoncodehk** [comment]
@mattersj correctly pointed out the problem, it is usually caused by an error inside TypeScript, and in .ts TypeScript will not show `[TS Error]` and just fails silently.

Volar's TypeScript runtime context is not exactly the same as VSCode built in TypeScript, because Volar is additionally affected by the imports types in .vue. So you may able to reproduce in .vue but not in .ts (when takeover mode and TypeScript Vue Plugin are turned off).

1. Disable takeover mode and TypeScript Vue Plugin, and reload VSCode.
1. Open `.../xxx.vue` and execute `Volar (Debug): Write Virtual Files` VSCode command. This will write all Volar's TS virtual files to the project to ensure that subsequent VSCode built in TypeScript gets the same project types context.
2. Open `.../xxx.vue.ts` and try auto import, the completion behavior that occurs with `[TS Error]` in .vue will silently fail in .ts.

**Comment by johnsoncodehk** [comment]
My fault, I found that when changing the cancel token to always respond true, I can always get `[TS Error] { }`, so https://github.com/johnsoncodehk/volar/commit/697b22ae4751d99d4cfc78950c89d859f5a44653 is likely to fix problem.

**Comment by mattersj** [comment]
@johnsoncodehk Unfortunately, the issue is still there even after upgrading to v1.0.18.
Interestingly, it occurs only if you already have at least one import.

```ts
import { ref } from 'vue';

watch... // <--- Autocomplete gives you [TS Error] {}
```
<img width="845" alt="image" src="https://user-images.githubusercontent.com/28510814/209554621-b2b6d4f0-8b83-4ab0-b207-4fe176594885.png">


but at the same time autocomplete works perfectly if you comment out the `import` line.
<img width="838" alt="image" src="https://user-images.githubusercontent.com/28510814/209554596-40092b0a-2b75-4f64-8e8b-8ae6ca69bffa.png">

**Comment by netitgo** [comment]
this bug still exists after update to `v1.0.18`

**Comment by johnsoncodehk** [comment]
This is a bug from TypeScript, but it can't reproduce in .ts because `tsserver` has additional logic for handling auto importing (It at https://github.com/microsoft/TypeScript/blob/68df4befd68c0325861bd5b87c6e4d251ffd5a41/src/server/project.ts#L1989-L2020), so it behaves differently than `vue-language-server` using a single typescript language service, and the additional logic just bypasses the bug coincidentally.

Here is a workaround for now.

1. Install [volar-1.0.19-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/10308333/volar-1.0.19-alpha.1.vsix.zip) which supports `autoImportFileExcludePatterns` setting by https://github.com/johnsoncodehk/volar/commit/0ed1cbcf16dcbc49aaa4512bc771fefa87c7a063.

2. Add `@vue/runtime-core`, `@vue/runtime-dom` to `autoImportFileExcludePatterns` in VSCode settings.

`.vscode/settings.json`:

```json
{
	"javascript.preferences.autoImportFileExcludePatterns": [
		"@vue/runtime-core",
		"@vue/runtime-dom"
	],
	"typescript.preferences.autoImportFileExcludePatterns": [
		"@vue/runtime-core",
		"@vue/runtime-dom"
	]
}
```

3. Reload VSCode.

**Comment by mattersj** [comment]
@johnsoncodehk I've tried it that way and it sometimes do really work but sometimes still fails.
Now I'm getting the following error when trying to auto-import `reactive` for example:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/28510814/209715285-c05bcf35-1b9b-4104-9a20-bf972dede978.png">

However, as I understand this workaround only works for `vue` anyway but not for any other library which is a bummer since this issue affects pretty much everything :(
Are there any chances for this to be fixed on the TS side or do we need another workaround that is going to work with any library?

**Comment by johnsoncodehk** [comment]
@mattersj If you do not rely on TS 4.9 features, you can temporarily downgrade to 4.8.3.

**Comment by mattersj** [comment]
@johnsoncodehk I haven't realized right away that this bug is related to the latest TS minor release, thanks for clearing this up.
I have a couple of `satisfies` in my project but I think it's worth removing them in return for working auto-import so I downgraded to 4.8.3 as you suggested, thank you!

**Comment by michaeldaw** [comment]
Thanks for everyone's efforts.

Is there an issue open in the Typescript project for the underlying issue? I'm not really up on the details, but it may be prudent for someone who better understands it to make one if not.

**Comment by johnsoncodehk** [comment]
@michaeldaw There was a similar issue in the past: https://github.com/microsoft/TypeScript/issues/46115

It's a bit difficult to provide the minimal reproduction needed for this issue, because as I said tsserver in *.ts just happens to bypass the issue. I have to done my other priorities first and then I will see if I can submit a PR for this .

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk I've tried it that way and it sometimes do really work but sometimes still fails. Now I'm getting the following error when trying to auto-import `reactive` for example:

@mattersj since `reactive` comes from the `@vue/reactivity` package, adding `@vue/reactivity` to autoImportFileExcludePatterns might handle this case for TS 4.9.

**Comment by mattersj** [comment]
@johnsoncodehk Yep, it handles this case but the issue is not only with `reactive` but with any other third-party library import such as `import { xxx } from 'vue-router'` so I don't think that listing all of these libraries is a better idea than just temporarily downgrading to 4.8.3 until a fix is rolled out.

**Comment by mgiraldo** [comment]
volar v1.0.24
vscode v1.74.3 (universal)

i'm getting a similar problem:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/133020/213607801-cbc67155-d9a5-43b4-b75b-e12d097a5d73.png">

volar keeps throwing this:

```
[TS Error] Error: Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol {}
```

and it is intermittent. reloading the vscode window sometimes gets it working but then after a few minutes it does again. i tried with and without `preferences.autoImportFileExcludePatterns` and it did not seem to make any difference. any ideas?

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/microsoft/TypeScript/pull/52686

**Comment by Nagell** [comment]
Nope, it's still there. Am I missing something?

Vue Language Features (Volar) - v1.2.0
TypeScript Vue Plugin (Volar) - v1.2.0
Typescript 4.9.5 (takeover)

![image](https://user-images.githubusercontent.com/4633237/221822051-a99204a2-5c53-41ba-be40-326caf567bc8.png)

**Comment by BARNZ** [comment]
Yeah looks like the fix is just not in any typescript release yet:

* Fix merged to main branch on Feb 11
* Latest ts release (v4.9.5) on Feb 1

**Comment by bazuka5801** [comment]
@BARNZ now we can install `typescript@next` (Feb 12), as I see the problem is gone ✅

**Comment by mgiraldo** [comment]
> @BARNZ now we can install `typescript@next` (Feb 12), as I see the problem is gone ✅

this is for the project/workspace typescript or for the operating system global typescript?

**Comment by wenfangdu** [comment]
Confirmed, ts v5.0.2+ doesn't have this issue:

![image](https://user-images.githubusercontent.com/28700378/227409935-bcbafdb2-ba61-4d6c-af0c-d1021770981d.png)

**Comment by CoderLadFahim** [comment]
I have the latest TS version, it's still not working for me.
Ironically, auto imports with take-over mode seem to be working everywhere except for Vue files.

Please help.

**Comment by ryanaltvater** [comment]
> if there is a way for me to share my current config i could paste it here.

Post a JSFiddle or CodePen link. I think it's funny that as soon as I come to this thread, I see 2 recent posts about something I'm experiencing this morning, but did not yesterday. Really odd.
