### ISSUE TITLE
For generic components, having two emits with different args as "v" causes the callback to infer "unknown"

### ISSUE THREAD

**Issue by alex-eliot** [vuejs/language-tools#3693]
Consider this generic input component:

```vue
<template>
  <input
    ref="input"
    :value="modelValue"
    @input="(e) => $emit('update:modelValue', (e.target as HTMLInputElement).value)"
    @keydown="e => e.code === 'Enter' && $emit('submit')"
  />
</template>

<script setup lang="ts" generic="T">

defineProps<{
  modelValue: T,
}>()

defineEmits<{
  (e: 'update:modelValue', v: T): void
  (e: "submit", v: void): void
}>()
</script>
```

If you use it in a template like this:

```vue
<template>
  <div>
    <GenericComponent
      :modelValue="val ?? ''"
      @update:modelValue="v => val = v"
    />
  </div>
</template>
```

The `v` value in the `@update:modelValue` callback will be of type `unknown`.

Rewriting the `(e: "submit", v: void): void` as `(e: "submit"): void` makes the language tools infer the generic type correctly.

I understand that in this specific case the `v: void` is unnecessary, but I just wanted to give a heads up in case it's an easy fix, otherwise you can close this issue.

**Comment by so1ve** [comment]
Not sure if we should fix this issue :(

**Comment by alex-eliot** [comment]
I understand how it's an issue with typescript overloading. I'm unsure if it worked before. but feel free to close this issue. I'm content so long as people like me can have something they can find it they encounter this issue, and know how to figure out workarounds.

**Comment by johnsoncodehk** [comment]
Type conversion breaks with `__VLS_NormalizeEmits`, not sure if fix is ​​possible.

```html
<script setup lang="ts">
const events!: __VLS_NormalizeEmits<{
    (e: "update:modelValue", v: number): void;
    (e: "submit", v: void): void;
}>;
events;
// ^? { [x: string]: (...args: unknown[]) => void; }
</script>
```

An alternative is to define events via defineProps.

```html
<script setup lang="ts" generic="T">
defineProps<{
    modelValue: T,
    'onUpdate:modelValue'(v: T): void,
}>()

defineEmits<{
    (e: "submit", v: void): void
}>()
</script>
```

**Comment by so1ve** [comment]
Mainly because `__VLS_ConstructorOverloads` cannot handle `void` type as arguments.

**Comment by KazariEX** [comment]
The problem is still existing now, but the final cause is ↓

![image](https://github.com/user-attachments/assets/09e71d2a-d998-4d2b-a3ad-5185f8341879)

Using named tuple syntax can alleviate it.

**Comment by ingoaf** [comment]
I think I found a similar issue now arising when using the `emitName: [emittype]` syntax.

[This playground example](https://play.vuejs.org/#eNqNVO9v0zAQ/VeMvzSVSjo09qVKqm2lEkNiTIBAgiCUJtfMm2MH2wmdqv7vnO0k/YW6fbPv3t353nvJml5VVdjUQCc00plilSEaTF1NE8HKSipD1kTBkmzIUsmSDBA66FN3qQJh2kw49lfbDSGJyKTQhpS6ILFtEQzeA+eSfJeK568Gw0REYz8RZ+HFQFnx1ADeCIl8r2nUNsVgNN5B0BE1GgcsWRE+aCnw+Wtbl9BMlhXjoD5VhuEDEjohLmNz2iiWGRsyqoZRF87uIXv84KB78Qe9srGE3inQoBpIaJ8zqSrAtUro/MstrPDcJ0uZ1xzRJ5KfQUte2yd62HUtcnz1Di5Fsv7eOKKZKL7q+cqA0N1O9qEWuXH4hCLpsxObb597Hr51dYnYIIlbyQ4NQHgqihgrsdHWDLN7xvNecHdr9e7cgkrve6UzgpYl3NblApT3Q7RgBUNlgwuBXuhQXBYedCXyG/2ONUyzBYfrpx+gJBYGwmUnxFePCDsEYUpKDqkYknjqGbCtMRRi87YeJ+6Hj9ogAjk6ZVHPRfMaBQWOTG0XTCi5rKsckROX/JbyGhBxcjmkOfKMHprd2b3n+hmh2q/OjkW6clgyAR/trecbJfpTMwW5d9Fmh30omemr5njRUftZHa1jvfTz5WL8Qjqnwc6oI+iRtlv9FO6pRJcncRyTM2uaZwTKWeMOeFzUxkhBLjPOskckyy4aDI6WGow8c//ZJHCJ4RBJntn/BcHumMemiydyFo39BD947Ccf/rF+N6BsBSp4Hl6Eb87p5h8SNOgj) seems to work in the playgroung, but the typecheck via `vue-tsc` on my machine fails with the error
```
error TS2322: Type '(number: bigint, isDivisibleByZero: boolean) => void' is not assignable to type '(...args: unknown[]) => any'.
  Types of parameters 'number' and 'args' are incompatible.
    Type 'unknown' is not assignable to type 'bigint'.

14   <Child v-model="someNumber" @update:modelValue="logNumberAndIsDivisibleByZero"></Child>
```

In the playground example I assume the `update:modelValue` from `defineModel` and defined in `defineEmits`: 
```ts
const emit = defineEmits<{
  "update:modelValue": [number: bigint, isDivisibleByZero: boolean]
}>()
```
collide. The same does not happen when defining the event via:
```ts
const emit = defineEmits<{
  (e: 'update:modelValue', number: bigint, isDivisibleByZero: boolean): void
}>()
```

(I still don't quite understand where the `(...args: unknown[]) => any` is coming from)

**Comment by KazariEX** [comment]
@ingoaf the type of `update:modelValue` event will be automatically generated, it will be intersected with the return type of `defineEmits`, then breaks.

**Comment by KazariEX** [comment]
> @KazariEX thank you!
> 
> Do you know how the generated type looks like, so the intersection ends up being `(...args: unknown[]) => any` ?

```ts
import { defineComponent } from "vue";

type __VLS_Emit = {
    "update:modelValue": [foo: string];
};

type __VLS_ModelEmit = {
    "update:modelValue": [foo: string];
};

const Comp = defineComponent({
    __typeEmits: {} as __VLS_Emit & __VLS_ModelEmit
});

new Comp().$emit;
```
