### ISSUE TITLE
Typescript errors are no more showed in the terminal since vue-tsc 2

### ISSUE THREAD

**Issue by vidal7** [vuejs/language-tools#4099]
# Description
On vue-tsc 2.0.6, console output is empty reporting no typescript errors even if there is an error

# Versions
- vue-tsc@2.0.6
- typescript@5.1.6
- vue@2.7.14
- node@20.10.0

Here is the error in vscode
![image](https://github.com/vuejs/language-tools/assets/33458053/5ba1f27a-1d9d-47c0-b6f9-07c1a43fe006)

# What is happening?
The output of the terminal is empty
![image](https://github.com/vuejs/language-tools/assets/33458053/4de5dd37-0996-4bd8-b15e-eef96820f0e8)

# What should I expect
![image](https://github.com/vuejs/language-tools/assets/33458053/381e348f-869a-4d85-9681-6de5a95cbd51)

# Steps to reproduce
- Clone the repo https://github.com/vidal7/volar-issue-vue-tsc-output
- Follow steps in readme.md

**Comment by vidal7** [comment]
I can add that upgrading to typescript version 5.4.2, console now showing something but incomplete.

![image](https://github.com/vuejs/language-tools/assets/33458053/e2d2ff7c-a918-498c-90f9-3b9404ecfb9b)

**Comment by AustinGrey** [comment]
Same issue, blank lines where the original code was supposed to be. Downgrade to vue-tsc 1.8.27 worked to restore the outputs in the console.

**Comment by ArchiDevil** [comment]
Same issue on vue@3.4.21, typescript@5.1.6. Upgrading TS to 5.4.3 shows empty lines on some errors (some are still fine). Downgrading to 1.8.27 helps.

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/volarjs/volar.js/commit/a4147851d85907f7eec662c55db49275d6d1ea6e

**Comment by wangshunnn** [comment]
> Fixed by [volarjs/volar.js@a414785](https://github.com/volarjs/volar.js/commit/a4147851d85907f7eec662c55db49275d6d1ea6e)

I'm very grateful for this bug fix, but I've reproduced the issue when using `--incremental` based on this fix:
1. When `vue-tsc --noEmit --incremental`, the first execution (without `tsconfig.tsbuildinfo`), everything works fine and a new `tsconfig.tsbuildinfo` cache file is generated.
2. Then, when executed repeatedly, the `.ts` file still prints the error as expected, but the `.vue` file no longer prints the source code for the error line.

With vue-tsc@2.0.7 Based on the latest fixed version：
"@volar/language-core": "2.2.0-alpha.3"
"@volar/typescript": "2.2.0-alpha.3"

**Comment by mr-sanders** [comment]
@johnsoncodehk I am not quite sure why the issue has been marked as closed. The fix in https://github.com/volarjs/volar.js/pull/158 was made in `@volar/typescript@2.2.0-alpha.4`, but the current `vue-tsc@2.0.19` depends on `@volar/typescript@~1.11.1`. Therefore, the issue still exists, and only downgrading to version 1.8.27 helps resolve it. Maybe it makes sense to reopen the issue?

**Comment by so1ve** [comment]
We are using @volar/typescript v2

**Comment by mr-sanders** [comment]
@so1ve You're right, I've got confused with dependency versions when switched packages. I'll remove my previous comment. So then I still have an issue with the following versions:
- `vue-tsc@2.0.19` (with `@volar/typescript@2.2.5`)
- `typescript@4.2.4`
- `node@16.20.2` (the same for `18.17.1`/`20.12.0`)

I tried to debug and found that the following `catch` swallows an error: https://github.com/vuejs/language-tools/blob/b80b63a5beff34b6bbc0a58a740e3fd13a97cf90/packages/tsc/index.ts#L52-L56

When I run

```bash
yarn run vue-tsc --noEmit
```
The issue it swallows is "createModuleResolutionCache is not defined".  It fails in `@volar/typescript` here: https://github.com/volarjs/volar.js/blob/f17c19f712651acde33cc2171a112e64db0b460e/packages/typescript/lib/node/proxyCreateProgram.ts#L58

The best I found is that `vue-tsc` tries to call `proxyCreateProgram` via `tsc` and passes empty proxy object instead of `ts` with the required methods. Is this the same issue or a new one?

**Comment by so1ve** [comment]
Seemed that your typescript version is too old, could you please upgrade to v5 if possible?

**Comment by mr-sanders** [comment]
@so1ve you're right. This is the problem. It's working for v5.

Probably it makes sense to specify the minimum supported version in `package.json` or readme. I checked `vue-tsc`'s `peerDependencies`, and it lists `"typescript": "*"`

**Comment by so1ve** [comment]
Sure, PR welcome :)
