### ISSUE TITLE
v3.0 Preview

### ISSUE THREAD

**Issue by johnsoncodehk** [vuejs/language-tools#5261]
#### 3.0.0-alpha.0 (2025-03-08)

- Change History: https://github.com/vuejs/language-tools/compare/v2.2.8...v3.0.0-alpha.0
- VSIX: https://github.com/vuejs/language-tools/actions/runs/13729716065/artifacts/2713802936

**Comment by Satont** [comment]
Is there webstorm alpa build?

**Comment by johnsoncodehk** [comment]
@Satont I think that's promising, @tomblachut has already confirmed the required adjustments!

**Comment by ilyarefraction** [comment]
I see you've made some changes to language service plugins here. Would you be able to support working with custom language service plugins in v3? I mean reintroduce changes from #1028 to make [volar/services](https://github.com/[volarjs/services](https://github.com/volarjs/services)) work again?

[Related issue](https://github.com/vuejs/language-tools/issues/4709)

**Comment by johnsoncodehk** [comment]
@Ilanaya LS plugin support is part of the 3.0 plan, but will not be supported via the reintroduction of volar.config.js.

**Comment by rodrigocfd** [comment]
I just tested 3.0.0-alpha.2, and it looks pretty good. I found no bugs so far.

**Comment by qiaozhu** [comment]
何时发布3.0版本

**Comment by spaceemotion** [comment]
I just installed alpha 3 and for some reason, the auto-complete is missing props on some components and seems incorrect?

![Image](https://github.com/user-attachments/assets/9bcbbba5-060f-4733-be25-0b51dd941ee9)

![Image](https://github.com/user-attachments/assets/339d698c-67d4-428b-a73b-ab834b99b081)

**Comment by KazariEX** [comment]
@spaceemotion Please provide a minimal reproduction.

**Comment by ehoogeveen-medweb** [comment]
Tried out alpha 2 with VSCode Remote Development (over SSH), but it seems to often cause the connection to close. It seems to reliably trigger when I go to view the extensions pane, but I've seen it happen seemingly at random too. I tried checking the logs on the remote, but all I could find was this:

```
exthost25/remoteexthost.log:
2025-04-02 10:48:41.095 [info] Extension host terminating: received terminate message from renderer

remoteagent.log:
2025-04-02 10:48:43.850 [info] [<unknown>][05fc3261][ExtensionHostConnection] <792972> Extension Host Process exited with code: 0, signal: null.
```
Here `exthost25` is just the most recent extension host. So it seems like a renderer crash, but no further information is given (no stack or error code).

Using VSCode v1.98.2 and Remote SSH v0.118.0 (both the latest as of right now), a Windows host and a Linux remote (but it seems to be the remote that crashes).

**Comment by hkochniss** [comment]
that sounds awesome.. _roughly_ when can we expect a release in VS market place? :)

**Comment by KazariEX** [comment]
Since semver pre-release tags are not supported on VSCode, we can't release these alpha versions at the moment.

Before the official version is released, we need to patiently wait for other editors to integrate the new architecture.

**Comment by KazariEX** [comment]
Sorry, I have updated the vsix link.

**Comment by Powersource** [comment]
https://github.com/vuejs/language-tools/issues/5349

**Comment by RayGuo-ergou** [comment]
Having the same issue with @spaceemotion, the completion items for a vue components only show 4 default entries: `data-allow-mismatch`, `ref`, `is` and `key`.

However if I manually type the prop/event, it can refer to the correct type, diagnostic for required props also works fine.

This issue happens from 'alpha 0'. Is it used some new 'feature' in LSP that require the LSP client to adopt?

Btw tried the vscode version, all work as excepted.

![Image](https://github.com/user-attachments/assets/fd840f2a-d605-4589-91a7-fc609a5ffe80)

**Comment by KazariEX** [comment]
v3.0 redesigned the communication method with tsserver.

**Comment by RayGuo-ergou** [comment]
I see, I think the issue is here:https://github.com/vuejs/language-tools/pull/5252/files#diff-3c2b2dc57146f5d52dc996ede798d28b5e6163dcd75762900a25803398a099edR89-R102

There's no `forwardingTsRequest` in neovim so it would not work. 

There should be a way to do it in neovim (I will play with it when i have time), but regardless to me this change limited the version 3 to work with vscode only.🤔

**Comment by johnsoncodehk** [comment]
@RayGuo-ergou "forwardingTsRequest" (now changed to "tsserverRequest") is not specific to VSCode. It is a command ID set by the language client, and the language server sends a forwarding request to the language client based on the command ID. (See: https://github.com/search?q=repo%3Avuejs%2Flanguage-tools%20tsserverRequest&type=code)

For other IDEs, what needs to be explored is how the Vue language client accesses the tsserver process so that the Vue language client can forward requests from the Vue language server to tsserver.

In VSCode the tsserver process is maintained by the built-in TS extension, and we [use a hack to access it](https://github.com/vuejs/language-tools/blob/5d2731321a8efca4e82677f37f6e10139d7e0043/extensions/vscode/src/nodeClientMain.ts#L160-L164).

**Comment by RayGuo-ergou** [comment]
Thanks for clarifying. Sorry did not make that clear, yeah I did mean there's a new custom command that the editors has to handle in some level. What I mean by 'work with vscode only' is that only the vscode plugin comes out of box with vue lsp.

But if there's a strong reason to do it in this way (i think there is: named pipe), should be fine as long as it properly documented.

 >For other IDEs, what needs to be explored is how the Vue language client accesses the tsserver process so that the Vue language client can forward requests from the Vue language server to tsserver.

I would imagine there's still work to do to achieve this in neovim I will let you know how i goes so there would not be a ton of issues after release 😄

**Comment by opengraphica** [comment]
Please mark these updates as pre-release when updating the extension. I have received unwanted crashes because of auto updates to this alpha version, and I'm sure most of your user base has as well.

**Comment by RayGuo-ergou** [comment]
![Image](https://github.com/user-attachments/assets/2783cb49-8967-4203-86b2-6eddb040a646)

Got version 3 working in neovim, need a bit of config

```lua
    volar = {
      init_options = {
        vue = {
          hybridMode = true,
        },
        typescript = {
          tsserverRequestCommand = 'tsserverRequest',
        },
      },
      on_init = function(client)
        client.handlers['tsserverRequest'] = function(error, result, context, config)
          dd(11)
          local ts_client = ergou.lsp.get_clients({ bufnr = context.bufnr, name = 'vtsls' })[1]

          local params = {
            command = 'typescript.tsserverRequest',
            arguments = unpack(result),
          }

          local res = ts_client:request_sync('workspace/executeCommand', params)

          dd(res)
		  --TODO: nil and error check
          return res.result.body
        end
      end,
      on_attach = function(client, _)
        client.server_capabilities.documentFormattingProvider = nil
      end,
    },
```

I manually modified the tsserver code tho, for all neovim users to work(even other editors e.g. i know zed uses `vtsls`), it has to patch upstream (either https://github.com/yioneko/vtsls or https://github.com/typescript-language-server/typescript-language-server)

I have created an issue on `vtsls` see: https://github.com/yioneko/vtsls/issues/249

**Comment by Tenrys** [comment]
With v3.0.0-alpha.6, it seems the template section cannot find variables that are meant to be globally imported through Nuxt. The script section works fine.

Getting errors like 
```
Property 'xxx' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<{}, {}>, ...>'.
```

**Comment by KazariEX** [comment]
@Tenrys Please open a issue with a minimal reproduction.

**Comment by seanogdev** [comment]
I'm not sure where to provide feedback but I've been seeing a memory leak happening since at least alpha 5, on our relatively large codebase.

Not sure thids will help but this is what the extension host is outputting while I get the JS/TS Initializing message

```
2025-05-17 22:15:23.931 [error] Error: Request vue/reactionsAnalyze failed with message: Cannot read properties of undefined (reading 'forEachChild')
    at be (/Users/sean/.vscode/extensions/vue.volar-3.0.0-alpha.7/dist/protocol-CMNNM7Cx.js:3:10625)
    at ge (/Users/sean/.vscode/extensions/vue.volar-3.0.0-alpha.7/dist/protocol-CMNNM7Cx.js:3:7168)
    at _e (/Users/sean/.vscode/extensions/vue.volar-3.0.0-alpha.7/dist/protocol-CMNNM7Cx.js:3:7290)
    at Immediate.<anonymous> (/Users/sean/.vscode/extensions/vue.volar-3.0.0-alpha.7/dist/protocol-CMNNM7Cx.js:3:7058)
    at processImmediate (node:internal/timers:483:21)
```

**Comment by johnsoncodehk** [comment]
@seanogdev Can you confirm the exact version causing the memory issue? This will help us locate the problem.

**Comment by seanogdev** [comment]
> @seanogdev Can you confirm the exact version causing the memory issue? This will help us locate the problem.

Happy to!

I've been away for a few weeks. Will help provide debugging data when back

**Comment by stouch** [comment]
We are testing the 3.0.0-alpha.8 on Cursor (built on VSC) MacOS since few days, and it works much better than the v2 (no resolution issues since then).

```bash
cursor --install-extension ~/Downloads/volar-3.0.0-alpha.8.vsix
```

**Comment by Caffeine19** [comment]
Are there any benchmarks comparing v2 and v3? I tried v3, but it still runs pretty slowly and makes my machine really hot.

**Comment by seanogdev** [comment]
Is anyone else seeing the following error when running the beta?

<details><summary>Details</summary>
<p>

```
2025-06-16 16:52:40.800 [error] TypeError: Cannot read properties of undefined (reading 'templateInterpolationDecorators')
    at a (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:80795)
    at /Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:80434
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:95274)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2443)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2660)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:62213)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at Ly.acceptDocumentsAndEditorsDelta (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:128:11752)
    at Ly.$acceptDocumentsAndEditorsDelta (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:128:10211)
    at $5.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116786)
    at $5.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116566)
    at $5.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115655)
    at $5.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114760)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113557)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:3443)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:1735)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:3073)
2025-06-16 16:52:40.800 [error] TypeError: Cannot read properties of undefined (reading 'reactionsVisualization')
    at o (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:85028)
    at /Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:84654
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:95274)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2443)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2660)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:62213)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at Ly.acceptDocumentsAndEditorsDelta (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:128:11752)
    at Ly.$acceptDocumentsAndEditorsDelta (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:128:10211)
    at $5.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116786)
    at $5.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116566)
    at $5.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115655)
    at $5.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114760)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113557)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:3443)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:1735)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:3073)
2025-06-16 16:52:40.800 [error] TypeError: Cannot read properties of undefined (reading 'focusMode')
    at u (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:83613)
    at /Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:83196
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:95274)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2443)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2660)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:62213)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at Ly.acceptDocumentsAndEditorsDelta (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:128:11752)
    at Ly.$acceptDocumentsAndEditorsDelta (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:128:10211)
    at $5.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116786)
    at $5.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116566)
    at $5.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115655)
    at $5.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114760)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113557)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:3443)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:1735)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:3073)
2025-06-16 16:52:40.803 [error] TypeError: Cannot read properties of undefined (reading 'focusMode')
    at u (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:83613)
    at /Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:83253
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:95274)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.C (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2443)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2660)
    at VG.$acceptEditorPropertiesChanged (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:63544)
    at $5.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116786)
    at $5.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:116566)
    at $5.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:115655)
    at $5.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:114760)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:113557)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at ud.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:3443)
    at P.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2373)
    at P.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:27:2591)
    at po.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:9458)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:361:1735)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:3073)
2025-06-16 16:52:40.902 [error] TypeError: Cannot read properties of undefined (reading 'reactionsVisualization')
    at o (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:85028)
    at Timeout._onTimeout (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:84775)
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7)
2025-06-16 16:52:46.207 [error] TypeError: Cannot read properties of undefined (reading 'templateInterpolationDecorators')
    at a (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:80795)
    at Timeout._onTimeout (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:80551)
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7)
2025-06-16 16:52:46.207 [error] TypeError: Cannot read properties of undefined (reading 'focusMode')
    at u (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:83613)
    at Timeout._onTimeout (/Users/sean.ogrady/.vscode/extensions/vue.volar-3.0.0-beta.2/dist/extension.js:5:83384)
    at listOnTimeout (node:internal/timers:588:17)
    at processTimers (node:internal/timers:523:7)
```

</p>
</details>

**Comment by johnsoncodehk** [comment]
@seanogdev There was an error in the packaging of beta.2, please reinstall `volar-3.0.0-beta.2.vsix.zip (built 2)`.

**Comment by Niefee** [comment]
When to provide Chinese description of settings

**Comment by RayGuo-ergou** [comment]
I believe its already supported:

https://github.com/vuejs/language-tools/blob/master/extensions/vscode/package.nls.zh-CN.json

**Comment by dkattan** [comment]
I tested 3.0.0-beta.3 and it still crashes the TS Server in VS Code when `"typescript.tsserver.experimental.enableProjectDiagnostics": true`

<img width="1756" alt="Image" src="https://github.com/user-attachments/assets/698467d8-76f7-40e8-92ef-5ad27e432f62" />

```
2025-06-24 05:22:54.857 [error] [Window] [122] potential listener LEAK detected, having 188 listeners already. MOST frequent listener (84):: Error
    at gEi.create (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:27:11906)
    at jWe.q [as onDidChangeFilesAssociation] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:29:1377)
    at Zye.wb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:9302)
    at new Zye (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:9229)
    at ESt.o (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1915:1589)
    at ESt.createInstance (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1915:1086)
    at twt.W (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3312:5820)
    at twt.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3312:5520)
    at tYe.r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:21367)
    at tYe.f (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:20981)
```
Edit: I thought it stopped happening when I opened just the frontend folder but it continues to happen.

**Comment by johnsoncodehk** [comment]
@dkattan This doesn't seem to be a regression, could you open an issue?

**Comment by dkattan** [comment]
> [@dkattan](https://github.com/dkattan) This doesn't seem to be a regression, could you open an issue?

There appears to be one already. I'll add details there: https://github.com/vuejs/language-tools/issues/4519

**Comment by Zephyrrro** [comment]
Is there a typescript version limit? In my environment, it always prompts "IntelliSense status is being loaded" （TS V5.0.2）

**Comment by johnsoncodehk** [comment]
@Zephyrrro TSDK requires at least 5.3 or above.

**Comment by johnsoncodehk** [comment]
We plan to release v3 after 3.0.0-beta.4, please update to 3.0.0-beta.4 and let us know if you find any regressions. 🙏

> I see you've made some changes to language service plugins here. Would you be able to support working with custom language service plugins in v3? I mean reintroduce changes from [#1028](https://github.com/vuejs/language-tools/pull/1028) to make [volar/services](https://github.com/%5Bvolarjs/services%5D(https://github.com/volarjs/services)) work again?
> 
> [Related issue](https://github.com/vuejs/language-tools/issues/4709)

Unfortunately after more research we have not found a suitable design to achieve this and this will not be added in 3.0. Can you open an issue describing what you would like to achieve with the plugin architecture?

> Are there any benchmarks comparing v2 and v3? I tried v3, but it still runs pretty slowly and makes my machine really hot.

This can be caused by many reasons, such as recursive type evaluation/heavy dependencies, etc. Please open an issue and provide a reproduction, otherwise we can't help.

**Comment by antlionguard** [comment]
@johnsoncodehk can you send new message when you publish new version? the subscribers can get notifications on new beta updates. thanks.

**Comment by Iamdyy** [comment]
![Image](https://github.com/user-attachments/assets/cff5c3fd-96b5-4ffc-b92e-48dead8eb20a)
不知道你们有没有遇到这个问题，经常新建一个vue文件，导致插件无法正常工作

3.0.0-beta.3 版本

**Comment by lucaslenz** [comment]
I'm on the current newest version of the complete toolchain and i'm not able to analyze templates with pug enabled.

I am using neovim and setup vtsls with vue-language-server. Everything works but analyzing templates with pug ends in a endless analyzing loop. The pug template is configured but there seems to be an issue with it.

The setup is like stated [here](https://github.com/vuejs/language-tools/wiki/Neovim) with some adjustments. When opening a vue file with template lang set to pug it hangs on the `_vue:projectInfo` command. When settings `skipTemplateCodegen` to false or when removing the pug plugin from the vueCompilerOptions it works but obivously skips the template analyzing.

Any ideas?

![Image](https://github.com/user-attachments/assets/5d9cdcef-5eac-4881-8ca6-7917521c4913)

Versions:

- @vue/language-server: v3.0.0-beta.4
- @vtsls/language-server: v0.2.9

package.json

```json
  "dependencies": {,
    "vue": "3.5.17",
  },
  "devDependencies": {
    "@tsconfig/node20": "20.1.6",
    "@typescript-eslint/parser": "8.29.0",
    "@typescript-eslint/utils": "8.29.0",
    "@vitejs/plugin-vue": "6.0.0",
    "@vue/eslint-config-prettier": "10.2.0",
    "@vue/eslint-config-typescript": "14.5.1",
    "@vue/language-plugin-pug": "3.0.0-beta.4",
    "@vue/tsconfig": "0.7.0",
    "eslint": "9.29.0",
    "eslint-plugin-cypress": "4.2.0",
    "eslint-plugin-prettier": "5.2.5",
    "eslint-plugin-storybook": "0.12.0",
    "eslint-plugin-vue": "10.2.0",
    "eslint-plugin-vue-pug": "0.6.2",
    "prettier": "3.3.3",
    "prettier-plugin-tailwindcss": "^0.6.13",
    "pug": "3.0.3",
    "tailwindcss": "^4.1.10",
    "typescript": "5.6.3",
    "typescript-eslint": "8.29.0",
    "vite": "6.2.5",
    "vite-plugin-html": "3.2.2",
    "vite-plugin-vue-devtools": "7.7.7",
    "vue-eslint-parser": "10.1.4",
    "vue-tsc": "2.2.10"
  }
```

tsconfig.app.json
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "vueCompilerOptions": {
    "plugins": ["@vue/language-plugin-pug"],
    "skipTemplateCodegen": false
  },
  "compilerOptions": {
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",

    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

lsp setup
```lua
        vtsls = {
          settings = {
            typescript = {
              tsserver = {
                maxTsServerMemory = 8192,
                watchOptions = {
                  watchFile = 'useFsEvents',
                  watchDirectory = 'useFsEvents',
                  fallbackPolling = 'dynamicPriority',
                },
              },
            },
            vtsls = {
              autoUseWorkspaceTsdk = true,
              tsserver = {
                globalPlugins = {
                  {
                    name = '@vue/typescript-plugin',
                    location = '/Users/lucas/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server',
                    languages = { 'vue' },
                    configNamespace = 'typescript',
                    enableForWorkspaceTypeScriptVersions = true,
                  },
                },
              },
            },
          },
          filetypes = { 'typescript', 'typescriptreact', 'javascript', 'javascriptreact', 'vue' },
        },
        vue_ls = {
          init_options = {
            typescript = { serverPath = '' },
          },
          on_init = function(client)
            client.handlers['tsserver/request'] = function(_, result, context)
              local ts_client = vim.lsp.get_clients({ bufnr = context.bufnr, name = 'vtsls' })[1]
              if not ts_client then
                vim.notify('vtsls client not running', vim.log.levels.ERROR)
                return
              end

              -- `result` is a table-of-tables: { { id, command, payload } }
              local id, command, payload = unpack(result[1])

              ts_client:exec_cmd(
                {
                  command = 'typescript.tsserverRequest',
                  arguments = { command, payload },
                },
                { bufnr = context.bufnr },
                ---@param err any
                ---@param res table|nil
                function(err, res)
                  if err then
                    vim.notify('vtsls error: ' .. vim.inspect(err), vim.log.levels.ERROR)
                    return
                  end
                  if not res or not res.body then
                    vim.notify(('vtsls returned no data for %s'):format(command), vim.log.levels.WARN)
                    return
                  end

                  client:notify('tsserver/response', { { id, res.body } })
                end
              )
            end
          end,
        },

**Comment by xerox0213** [comment]
Hello, i use Vue Language Server 3 (thanks for that) in beta 4 but i have some problems in VSCode :

- When i type Vue elements like `ref`, i do not have auto-complete suggestions, i have to import manually
- When i switch to another component i have an infinite loop with this message : **_"Analyzing 'ComponentName' and its dependencies_"** i never had that in beta 3 or any older version.
- Imagine i have a component name "**_ArticleCard_**", if i type `<Article` in a template, it does not suggest me the component but only the native HTML element, i have to press esc -> erase one or few letters -> trigger again the auto-completion and then it displays the component name (idk if it's related of VLS or VsCode)
- Sometime when i create a new SFC, VLS does not recognize it, nothing works (auto-suggestions, ...)

<img width="1133" alt="Image" src="https://github.com/user-attachments/assets/35a07aea-2f81-4623-ad85-285ef07e8b44" />

**Comment by johnsoncodehk** [comment]
@lucaslenz I can't reproduce this problem in VSCode, can you open an issue to help us investigate? Following informations that helps us:

1. Does it work in v3+VSCode?
2. Does it work in v2+nvim?
3. A repo that can reproduce the problem

**Comment by johnsoncodehk** [comment]
@xerox0213 Could you contact us for an investigation?

https://github.com/vuejs/language-tools/wiki/Help-Us-Investigate-Issues-Remotely

**Comment by xerox0213** [comment]
> [@xerox0213](https://github.com/xerox0213) Could you contact us for an investigation?
> 
> https://github.com/vuejs/language-tools/wiki/Help-Us-Investigate-Issues-Remotely

Yeah of course, i will contact you tomorrow !

**Comment by ilyarefraction** [comment]
> Unfortunately after more research we have not found a suitable design to achieve this and this will not be added in 3.0. Can you open an issue describing what you would like to achieve with the plugin architecture?

@johnsoncodehk I decided to add a more detailed explanation in the existing issue rather then creating a new one. I wrote some details about my use case in #4709 [here](https://github.com/vuejs/language-tools/issues/4709#:~:text=Ordering%C2%A0%231005-,Real%20world%20case,-We%20have%20a)

**Comment by xerox0213** [comment]
@johnsoncodehk Sorry i had not the time for the remote investigation during the week end, but i have tested the V5 and all the bugs that i had are fixed, so thanks a lot !

**Comment by johnsoncodehk** [comment]
It's released!
https://github.com/vuejs/language-tools/releases/tag/v3.0.0

**Comment by hkochniss** [comment]
bug: when I import some internal library under the `/src/libs/mylib/subpath` folder in my `/src/components/Component.vue`, it will always import the wrong path:
`libs/mylib/subpath`
instead of the correct
`../libs/mylib/subpath`

Really annoying, please fix before going wide

Edit: tried with released 3.0 Vue tools.. bug still exists

<details>
<summary>Here's my tsconfig.json</summary>


```
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "target": "ESNext",
    /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    "lib": ["ESNext", "DOM"],
    /* Specify what JSX code is generated. */
    "jsx": "react-jsx",

    /* Specify what module code is generated. */
    "module": "ESNext",
    /* Specify how TypeScript looks up a file from a given module specifier. */
    "moduleResolution": "bundler",
    /* Specify type package names to be included without being referenced in a source file. */
    "types": ["./worker-configuration.d.ts"],
    /* Enable importing .json files */
    "resolveJsonModule": true,

    /* Allow JavaScript files to be a part of your program. Use the `checkJS` option to get errors from these files. */
    "allowJs": true,
    /* Enable error reporting in type-checked JavaScript files. */
    "checkJs": false,

    /* Disable emitting files from a compilation. */
    "noEmit": true,

    /* Ensure that each file can be safely transpiled without relying on other imports. */
    "isolatedModules": true,
    /* Allow 'import x from y' when a module doesn't have a default export. */
    "allowSyntheticDefaultImports": true,
    /* Ensure that casing is correct in imports. */
    "forceConsistentCasingInFileNames": true,

    /* Enable all strict type-checking options. */
    "strict": true,

    /* Skip type checking all .d.ts files. */
    "skipLibCheck": true,

    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

</details>

**Comment by johnsoncodehk** [comment]
3.0 has been officially released. Please open a separate issue for issues after 3.0. Thank you.

This issue will be locked.
